### ISSUE TITLE
ATM7 networking issues 

### ISSUE THREAD

**Issue by liviniumnetwork** [iPortalTeam/ImmersivePortalsModForForge#10]
### According to your testing, does the issue occur with ONLY Immersive Portals mod?

No

### Forge Version

40.1.68

### ImmersivePortals Version

immersive-portals-1.4.9-rc3-mc1.18.2-forge.jar

### Latest Log

https://gist.github.com/liviniumnetwork/57938a5829d501e51b7c3d8bff9834f5

### Crash Report (if applicable)

Client Does not crash

### Steps to Reproduce

1: Have All The Mods 7 installed & put immersive-portals-1.4.9-rc3-mc1.18.2-forge.jar into mod folder.
2: Launch the game, try to join a compatible server.
3: Be kicked multiple times before you can get into the server with the error message.

### What You Expected

Should of loaded into the server as normal without issue, now with cool portals again on 1.18.2 :D

### What Happened Instead

Get kicked out of the server with the error "Internal exception: Java.Lang.nullPointerException: Cannot invoke “net.minecraft.network.protocol.Packet.m5797(net.minecraft.network.PacketListener)” because “packet” is null"

### Additional Details

Removing the immersive portals mod lets me connect to my server (Its a private server that I run so I can change as need be).
Optifine is not installed, I use multiple mods to achieve what optifine does. 
Disabling my shaders and trying again results in the same error regardless, hence why reporting here.

I have tried to search the error but I find nothing on it hence why reporting here, sorry if this is not where it belongs but as stated before removing the immersive portals mod clears the issue & can play as normal.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Just to make sure, you did install Immersive Portals server- and clientside?

**Comment by liviniumnetwork** [comment]
Yes of course, it was both client & server side installed.

**Comment by liviniumnetwork** [comment]
I accidentally closed the issue🥴 Was on phone, issue not solved^

**Comment by Nick1st** [comment]
Ok then. Please send me a client and a server log containing the same login attempt.

**Comment by liviniumnetwork** [comment]
[latest-client.log](https://github.com/iPortalTeam/ImmersivePortalsModForForge/files/9425503/latest-client.log)
[latest-server.log](https://github.com/iPortalTeam/ImmersivePortalsModForForge/files/9425504/latest-server.log)

These are the latest, restarted the server and reinstalled the mod too on both ends just to see if anything changes, but it does not.

**Comment by Nick1st** [comment]
Twilight Forest is incompatible with Immersive Portals. They are doing something wrong with there dimension. I don't think this is causing this issue. Note though, that with Twilight Forest installed, more serious errors, like breaking worlds, may arise.

**Comment by liviniumnetwork** [comment]
Ah alright, well I dont think anyone on the server even uses Twilight Forest so I can always remove it. Something else I should note here is that when using shaders (I am able to get into single player with immersive portals and everything else) the entire world turns red.
I have attached an image so you can see what I mean, they used to work when I used immersive portals on 1.16, so not sure if this is their issue or if it belongs here.
I have not tested other shaders.
![Base Profile Screenshot 2022 08 25 - 02 26 14 65](https://user-images.githubusercontent.com/82018786/186695617-9f9ff9d0-e20c-4660-a75f-c0e7e3bf6fbc.png)

**Comment by Nick1st** [comment]
Please open a new issue for that.

**Comment by alexandros7orion77** [comment]
Having the same issue and the same log errors.

**Comment by Dezzixr** [comment]
I'm _really_ sorry for taking the issue hostage like this, but this is *exactly* the issue i'm facing. I'm running Connectivity to get rid of payload errors, but with both Connectivity and Immersive Portals both installed, i get the same "Internal exception: Java.Lang.nullPointerException: Cannot invoke “net.minecraft.network.protocol.Packet.m5797(net.minecraft.network.PacketListener)” because “packet” is null" error.

Removing Immersive Portals gets rid of the issue.

I _really_ want to use Immersive Portals though, any idea what could be done to fix it?

**Comment by Nick1st** [comment]
Ah, I didn't notice connectivity. That's the issue here. Tracked in #21
