### ISSUE TITLE
[Feature Request] Allow Dimension Stacking to be Set in Config as Default

### ISSUE THREAD

**Issue by Darkosto** [iPortalTeam/ImmersivePortalsModForForge#100]
Hello,

Would you be willing to look into making the dimension stacking option a default setting in the mod config? I'd like to setup a number of dimensions ahead of time for my modpack and currently there exists no way to do that short of looking for a mod to copy data files into the save file. 

Thank you!
Darkosto

Minecraft: 1.18.2
Forge: 40.2.0
Immersive Portals: 1.4.13

**Comment by Nick1st** [comment]
This has already been requested and is on my todo list.

I've watched some bits from your stream. You should probably read through some wiki pages if you haven't already:

- https://qouteall.fun/immptl/wiki/Dimension-Stack.html
- https://qouteall.fun/immptl/wiki/Config-Options.html
- https://qouteall.fun/immptl/wiki/Miscellaneous.html#can-fluid-redstone-and-light-work-across-a-portal
- https://qouteall.fun/immptl/wiki/Implementation-Details.html

If you've any questions I highly suggest you to join the official discord server: https://discord.gg/BZxgURK

**Comment by Darkosto** [comment]
Thanks for the response and information @Nick1st 

Have a wonderful rest of your day!

**Comment by qouteall** [comment]
The dimension stack preset feature was  added in 1.19.x. And the preset only works on client now (I am going to make it also work in dedicated server).

**Comment by Nick1st** [comment]
I'll backport it, as I've been asked by a ton of people.

**Comment by Nick1st** [comment]
@Darkosto [New version with global Dim Stack Config](https://www.curseforge.com/minecraft/mc-mods/immersive-portals-for-forge/files/4488791). Let me know if you find any problems with it.

How to use:

1. Set the new `editDimensionStackConfig` option in the main config to `true`.
2. Create a new world, open the dimension stack configuration screen and configure a dimensionstack.
3. Hit Save in the top right corner. (Note: Pressing this button will overwrite the existing saved config.)
4. This creates a file with the dimensionstack config, that you can also edit manually.
5. Setting the `editDimensionStackConfig` option in the main config back to `false` will hide the save configuration button from that menu again.

**Comment by Darkosto** [comment]
Hey @Nick1st 

Thanks for putting that update out! I just loaded everything up in a fresh instance and I'm not seeing the config option in a brand new generated config file. I checked the server config files and it's not located there either. I also tried adding the `editDimensionStackConfig` to the config manually but it was removed after starting up my MC instance. Is the config located elsewhere?

**Comment by Nick1st** [comment]
Oh, I named it `enableGlobalDimensionStack`. Sorry.

**Comment by Darkosto** [comment]
My mistake on not seeing the new config option right away. Just got everything setup and saved to the new file. All worlds are loading correctly as stacked with no need to change anything afterwards. Looks good to me 👍 

Thank you again for taking the time and putting that together, I appreciate your hard work
