### ISSUE TITLE
Cannot uninstall

### ISSUE THREAD

**Issue by GenDutchman** [iPortalTeam/ImmersivePortalsModForForge#111]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

44.1.23

### ImmersivePortals Version

2.5.4-mc1.19.3

### Latest Log

https://gist.github.com/GenDutchman/65ba96cd87b4ff8ba586f02e66b58b7f#file-debug-3-log

### Steps to Reproduce

Installed the mod,
Didn’t work with optifine
Removed mod from mod pack
Server didn’t start up
Removed config and dimension
Server didn’t start up

### What You Expected

I thought the server was going to go back and start up like it has done with other removing mods

### What Happened Instead

The issue that happened is described in the file link hopefully

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by qouteall** [comment]
MC saves dimension config in `level.dat` and it cannot be deserialized after uninstalling the mod. As far as I know Forge already solves this issue. Seems that the Forge's fix is broken? If the Forge's fix is broken, uninstalling other dimension mods could also lead to the same result. This is maybe a Forge's issue.

The quick solution is to create a new world with the same seed and configuration, then use the new world's `level.dat` to replace the broken world's `level.dat` (don't forge to backup the original `level.dat`).

**Comment by GenDutchman** [comment]
So, backup the world to begin with, create a new world with the same seed, copy the level.dat and replace the broken world’s level.dat with the new one.

Would it be better if I copied the level.dat from a previous save?

**Comment by GenDutchman** [comment]
> MC saves dimension config in `level.dat` and it cannot be deserialized after uninstalling the mod. As far as I know Forge already solves this issue. Seems that the Forge's fix is broken? If the Forge's fix is broken, uninstalling other dimension mods could also lead to the same result. This is maybe a Forge's issue.
> 
> The quick solution is to create a new world with the same seed and configuration, then use the new world's `level.dat` to replace the broken world's `level.dat` (don't forge to backup the original `level.dat`).

Could I also just use NBT Explorer and delete the dimensions from immersive portals?

**Comment by GenDutchman** [comment]
This is also for a server, and I can’t see player data in the level.dat NBT, I was looking around and saw some stuff that said level.dat stores player data in single player, but nothing about it storing player data on server level.dat.

**Comment by GenDutchman** [comment]
Ok Ok, I’ve tested it, using NBT Explored I removed the dimensions in the level.dat file, (I backed it all up first) then I removed the mods, the dimensions in the world save, the configs.
All is working now, thanks heaps for the help
