### ISSUE TITLE
1.16.5, nothing rendering

### ISSUE THREAD

**Issue by gradientogames** [iPortalTeam/ImmersivePortalsModForForge#114]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

36.2.20

### ImmersivePortals Version

0.17-mc1.16.5

### Latest Log

no log

### Crash Report (if applicable)

no crash

### Steps to Reproduce

1. Join a world
2. nothing rendering

### What You Expected

To see stuff

### What Happened Instead

couldn't see anything

### Additional Details

creating a nether portal and lighting it does work but the nether doesn't load either, only its skybox.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by gradientogames** [comment]
I am aware the 1.16.5 forge version does not paly nicely because of some sort of dynamic dimension feature.

**Comment by Nick1st** [comment]
We do no longer support 1.16.
