### ISSUE TITLE
[Technically a suggestion] 1.19.4 UPDATE!!!!!!!!!!!!!

### ISSUE THREAD

**Issue by Steve982950** [iPortalTeam/ImmersivePortalsModForForge#117]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

45.0.64

### ImmersivePortals Version

1.5 mc1.19.4

### Latest Log

N/A

### Crash Report (if applicable)

N/A

### Steps to Reproduce

1. Go to Curseforge page
2. CANT SPOT 1.19.4! CREATE IT NOW

### What You Expected

I EXPECTED A 1.19.4 forge VERSION!!!

### What Happened Instead

THE OWNER PUT IT TO A LAME VERSION

### Additional Details

I. WANT. 1.19.4!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Steve982950** [comment]
MAKE A 1.19.4 UPDATE OR I HATE YOUR MOD

**Comment by Nick1st** [comment]
Why should I care, rude 5 year old?
