### ISSUE TITLE
[1.16.5] All Blocks invisible with use of Rubidium in any configuration

### ISSUE THREAD

**Issue by grimmspector** [iPortalTeam/ImmersivePortalsModForForge#122]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

No

### Forge Version

36.2.39

### ImmersivePortals Version

0.17-mc1.16.5

### Latest Log

https://gist.github.com/grimmspector/6a3f39ee0e0750784ac3cc9ca263efde

### Steps to Reproduce

1. Load Rubidium + Immersive Portals in 1.16.5 Minecraft with Forge Mod Loader
2. Create a world or load a world
3. See only entities, all blocks are invisible regardless of resource pack selections or other video settings, no shaders or other advanced things are utilized.

### What You Expected

I expected things to render normally even if the mod failed to function for some reason

### What Happened Instead

Nothing was visible so it's unplayable in this state

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
1.16 is no longer supported. Please upgrade.
