### ISSUE TITLE
[Oculus] Outdated support

### ISSUE THREAD

**Issue by MrTangoPIG** [iPortalTeam/ImmersivePortalsModForForge#128]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

No

### Forge Version

43.2.14

### ImmersivePortals Version

immersive-portals-2.3.5-mc1.19.2-forge

### Latest Log

https://gist.github.com/MrTangoPIG/42b9c8303408b76fbd56bae1dd63f026

### Crash Report (if applicable)

https://gist.github.com/MrTangoPIG/dd814b0027e8a783200c372d170f4af1

### Steps to Reproduce

1st instance:
Open game
load world
Open shaders options
Apply shader
Crash

2nd instance (and i guess thereafter without disabling the shader pre-launch):
Open game
Crash

### What You Expected

?

### What Happened Instead

??

### Additional Details

ModList (generated via curseforge):
Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)
Miner's Delight + (by soytutta)
Create Confectionery (by Furti_Two)
Biomes O' Plenty (by Forstride)
Elytra Slot (Fabric/Forge/Quilt) (by TheIllusiveC4)
Carry On (by Tschipp)
Charm of Undying (Fabric/Forge/Quilt) (by TheIllusiveC4)
HT's TreeChop (by hammertater)
Diet (Fabric/Forge/Quilt) (by TheIllusiveC4)
CreativeCore (by CreativeMD)
TerraBlender (Forge) (by TheAdubbz)
Mysterious Mountain Lib (by sz0999312)
Auto Ore Dictionary Converter (by MattDahEpic)
Every Compat (Wood Good) (by MehVahdJukaar)
Dynamic Surroundings Resurrected (by theNyfaria)
SuperMartijn642's Config Lib (by SuperMartijn642)
Double Doors (by Serilum)
Collective (by Serilum)
Puzzles Lib [Forge & Fabric] (by Fuzs)
Easy Magic [Forge & Fabric] (by Fuzs)
Guard Villagers (by almightytallestred)
Immersive Portals (for Forge) (by qouteall)
Flywheel (by jozufozu)
Macaw's Doors (by sketch_macaw)
BucketLib (by thecech12)
Wool Tweaks (by Serilum)
Spiky Spikes (by Fuzs)
Cloth Config API (Fabric/Forge) (by shedaniel)
Farmer's Respite (by lumpazl)
Ecologics (by SameDifferent)
Citadel (by sbom_xela)
Spice of Life: Apple Pie Edition (by Anthxny)
Nether's Delight (by lumpazl)
CorgiLib (by Corgi_Taco)
Create (by simibubi)
Ender's Delight (by Furti_Two)
Corn Delight (by sz0999312)
Curios API (Forge) (by TheIllusiveC4)
Iris & Oculus Flywheel Compat (by leon_mout)
Effective (Forge) (by BottomTextDanny)
Easy Anvils [Forge & Fabric] (by Fuzs)
Farmer's Delight (by vectorwing)
[Let's Do] API (by Cristelknight)
Magnesium/Rubidium Extras (by Anthxny)
Nyf's Spiders (by theNyfaria)
Architectury API (Fabric/Forge) (by shedaniel)
Oculus (by Asek3)
Wooden Bucket (by thecech12)
Just Enough Items (JEI) (by mezz)
MattDahEpic Core (MDECore) (by MattDahEpic)
Chunk Loaders (by SuperMartijn642)
SuperMartijn642's Core Lib (by SuperMartijn642)
Moonlight Lib (by MehVahdJukaar)
Hearth & Home (by Starfish_Studios)
Alex's Mobs (by sbom_xela)
Ocean's Delight (by scouter567)
Magnesium/Rubidium Dynamic Lights (by Anthxny)
Immersive Weathering [FORGE] (by OrdanaryMods)
Blueprint (by TeamAbnormals)
Italian Delight (A Farmer's Delight Add-on) (by PuurpZ)
Leave My Bars Alone (by Fuzs)
Just Enough Resources (JER) (by way2muchnoise)
AmbientSounds 5 (by CreativeMD)
Another Furniture (by Starfish_Studios)
Croptopia (by thethonk)
Create: Steam 'n' Rails (by mattentosh)
Alex's Delight (by NCP_Bails)
Rubidium (by Asek3)
Clumps (by Jaredlll08)
Cultural Delights (by NCP_Bails)
[Let's Do] Vinery (by satisfy)
Enhanced Celestials - Blood, Blue, & Harvest (Super) Moons (by Corgi_Taco)
Caelus API (Forge) (by TheIllusiveC4)
Compat O' Plenty (by tdstress)
Macaw's Trapdoors (by sketch_macaw)
Drip Sounds (Forge) (by PieKing1215)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Downgrade Oculus.

**Comment by MrTangoPIG** [comment]
Installed version to oculus-mc1.19.2-1.2.8a.jar getting crash...
*does oculus need specific rubidium versions (and so on down dependency line)?

**Comment by drakosoldier298** [comment]
seems oculus support on 1,19,2 is still outdated.
https://mclo.gs/K7lKK4o

**Comment by Nick1st** [comment]
Yes it is, thus this issue is still open...

**Comment by AmazingKing9** [comment]
I'm having the exact same issue on 1.18.2 right now

**Comment by Soldier874** [comment]
### Is it a mod compatibility issue?

Yes

### Minecraft version

1.19.2

### Oculus Version

oculus-mc1.19.2-1.2.8a.jar / oculus-mc1.19.2-1.6.4.jar

### Sodium Version

rubidium-0.6.2b.jar

### Operating System

Windows 11

### What is your GPU?

RTX 4070Ti

### Java Version

java 1.7.0.3 64 Bits

### Reproduction Steps

Hello, i have a problem, it is possible to solve it? How can i have the three mod without problem of render or crash? :/

With oculus-mc1.19.2-1.2.8a.jar no problem with immersive-portals-2.3.5-mc1.19.2-forge.jar but the render of the bar of Neat mod is BAD

![2023-07-20_03 50 29](https://github.com/Asek3/Oculus/assets/118959698/443a3846-d1b4-4a55-8abe-562274a35bce)

=========================================================


With oculus-mc1.19.2-1.6.4.jar when I DISABLE immersive-portals-2.3.5-mc1.19.2-forge.jar but the render with the bar of Neat mod is fine

![2023-07-20_04 00 59](https://github.com/Asek3/Oculus/assets/118959698/4468a54d-454d-47c2-ab2e-fbab4aa2dac4)

=========================================================

With oculus-mc1.19.2-1.6.4.jar crash with immersive-portals-2.3.5-mc1.19.2-forge.jar /!\

### Crash Report file and latest.log

[crash-2023-07-20_03.57.24-client.txt](https://github.com/Asek3/Oculus/files/12101472/crash-2023-07-20_03.57.24-client.txt)

[latest.log](https://github.com/Asek3/Oculus/files/12101495/latest.log)

### Additional context

_No response_

**Comment by ColonelGerdauf** [comment]
It has been cited by the people on the Oculus/Rubidium server that the actual fault is on the side of this mod.

And they provide a specific example of `getTerrainVertexShaderSource`; according to them, this method no longer exists in Oculus or Iris.

**Comment by F0x06** [comment]
Hi, any updates on this ?
