### ISSUE TITLE
entities stall.. stop then move super fast - server only

### ISSUE THREAD

**Issue by DeadmanTheGod** [iPortalTeam/ImmersivePortalsModForForge#129]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

43.2.14

### ImmersivePortals Version

immersive-portals-2.3.5-mc1.19.2-forge

### Latest Log

https://gist.github.com/DeadmanTheGod/ecd89be7849923ed94ba6e5c38672bcd

### Steps to Reproduce

install immersive-portals-2.3.5-mc1.19.2-forge on an apex server 
log in 
go to a mob 
watch the mob entities stall.. stop then move super fast 

### What You Expected

if any mayb like slight lag

### What Happened Instead

mobs look like they on their 20th cup of coffee 

### Additional Details

this only happens on the server. single player i dont get lag. i have sorted thru mods.,.. deleted mods ..  added performance mods, the mod versions, nothing works .. i even upgraded the server thinking that would help but it didnt..  

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Can you maybe add a video to the issue showcasing the lag?

**Comment by Nick1st** [comment]
Also, please post the output of `/forge tps`.

**Comment by Nick1st** [comment]
Oh, and I'd need the server log as well please

**Comment by DeadmanTheGod** [comment]
hmmm i guess it fixed when i deleted the config files last night .. i will monitor it for a while n post what u need if it happens again cuz it did take a while for it to happen the last time... if it doesnt happen i will close the ticket myself in 3 days

**Comment by DeadmanTheGod** [comment]
i forgot to close this .. ik the issue n its another mod that needs an update n is getting the update that is interacting bad with this mod
