### ISSUE TITLE
Entering the portal causes Curios API items to disappear

### ISSUE THREAD

**Issue by Gamephantom** [iPortalTeam/ImmersivePortalsModForForge#13]
### According to your testing, does the issue occur with ONLY Immersive Portals mod?

No

### Forge Version

40.1.73

### ImmersivePortals Version

1.4.9-rc3-mc1.18.2

### Latest Log

https://gist.github.com/Gamephantom/4248142a4d3ba221f93b6c42e20e8955

### Steps to Reproduce

1. Equip an trinket in one of the Curios API Slots
2. Jump through an portal
3. Look at the Curios API slots

### What You Expected

All trinkets are still there and functional.

### What Happened Instead

All trinkets disappered and the effects of the trinkets also disappeared.

### Additional Details

After an restart, all Curios API Items are in their slots or if you enter an vanilla portal.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Fixed in the latest version.
