### ISSUE TITLE
NVIDA driver (535.54.03+) bug that causes a crash on Linux

### ISSUE THREAD

**Issue by Vitamin-X** [iPortalTeam/ImmersivePortalsModForForge#135]
### Is it a mod compatibility issue?

No

### Minecraft version

1.19.2

### Describe the issue

Game crashes after being around 3min long in the game

i tried to play the FTB Direwolf20 mod pack with Immersive Portals and notice it crashes really fast, removed all mods except Immersive Portals, still crashes also with a new world.

tried different java versions, all crashed.
also tried different forge versions, in some the game didn't even start.
tried a modpack for minecraft 1.20.1 with fabric, also crashed.

Is it maybe a Linux thing ? cuz i use xUbuntu, and normally mod devs don't care about Linux, and cant remember when they used upper letters in paths or not. 

I can see something about NVIDIA in the log files, so is maybe the driver "broken" also when everything else works fine?

[debug.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/12188525/debug.log)
[crash_log.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/12188529/crash_log.log)

**Comment by Nick1st** [comment]
What's your GPU? This is likely a driver issue, as the crash occurs somewhere in native code. Please also get me the output of 'lshw -c video'

**Comment by Vitamin-X** [comment]
its an RTX 3070 Mobile

#lshw -c video
  *-display                 
       Beschreibung: VGA compatible controller
       Produkt: GA104M [GeForce RTX 3070 Mobile / Max-Q]
       Hersteller: NVIDIA Corporation
       Physische ID: 0
       Bus-Informationen: pci@0000:01:00.0
       Logischer Name: /dev/fb0
       Version: a1
       Breite: 64 bits
       Takt: 33MHz
       Fähigkeiten: pm msi pciexpress vga_controller bus_master cap_list rom fb
       Konfiguration: depth=32 driver=nvidia latency=0 mode=1920x1080 visual=truecolor xres=1920 yres=1080
       Ressourcen: iomemory:600-5ff iomemory:620-61f irq:195 memory:83000000-83ffffff memory:6000000000-61ffffffff memory:6200000000-6201ffffff ioport:4000(Größe=128) memory:84080000-840fffff
  *-display
       Beschreibung: VGA compatible controller
       Produkt: TigerLake-H GT1 [UHD Graphics]
       Hersteller: Intel Corporation
       Physische ID: 2
       Bus-Informationen: pci@0000:00:02.0
       Logischer Name: /dev/fb0
       Version: 01
       Breite: 64 bits
       Takt: 33MHz
       Fähigkeiten: pciexpress msi pm vga_controller bus_master cap_list rom fb
       Konfiguration: depth=32 driver=i915 latency=0 resolution=1920,1080
       Ressourcen: iomemory:620-61f iomemory:400-3ff irq:176 memory:6202000000-6202ffffff memory:4000000000-400fffffff ioport:5000(Größe=64) memory:c0000-dffff memory:4010000000-4016ffffff memory:4020000000-40ffffffff



the driver is also the newest installed, without Immersive Portals the game also works fine.

**Comment by Nick1st** [comment]
Thanks. Do you have Rubidium installed? If not, please add it and check if the issue persists.

**Comment by Nick1st** [comment]
Actually, nevermind. Rubidium does not currently contain the workaround for NVIDIA's stupid driver...

**Comment by Nick1st** [comment]
Btw, I'm also on linux, but on much older hardware...

**Comment by Nick1st** [comment]
See: https://github.com/NVIDIA/open-gpu-kernel-modules/issues/522
See: https://bugs.mojang.com/projects/MC/issues/MC-263184
See: https://github.com/CaffeineMC/sodium-fabric/pull/1900

**Comment by Vitamin-X** [comment]
hello fellow tuxian

i remember these days when i got 20 times the frames in minecraft on linux then windows, java usually runs really bad on windows.

but new hardware and linux isnt soo easy to handle as older hardware back then, installing Linux on an old machine and you are ready to go.

on my notebook oh dear, after installing the notebook it didnt stay on longer then 10 mins cuz the OS wasnt able to speak to the fans and the notebook goes into a panic mode and turns off. and getting optimus running isnt an easy task too.

...
![grafik](https://github.com/iPortalTeam/ImmersivePortalsModForForge/assets/8036752/1fdea1eb-ffee-4f6f-aab1-187fdefc012a)
do you think another driver version would help?

**Comment by Nick1st** [comment]
:man_shrugging: try?

**Comment by Lolothepro** [comment]
fixed with NVIDIA 545 driver

**Comment by Nick1st** [comment]
Ok, good to know. I'll mark this as resolved then :+1: 
Will keep this open however and pin it, as those drivers aren't yet in the ubuntu stable repos.

**Comment by Nick1st** [comment]
Fixed drivers are now in Ubuntu stable repos, however they are still not recommended. Closing for now, but leaving pinned.
