### ISSUE TITLE
 Immersive Portals Core (imm_ptl_core) has failed to load correctly

### ISSUE THREAD

**Issue by Pichu6** [iPortalTeam/ImmersivePortalsModForForge#136]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

forge-1.19.3-44.1.23

### ImmersivePortals Version

2.5.4-mc1.19.3-forge

### Latest Log

https://gist.github.com/Pichu6/4a843f4f03630e4153bd08a38937e471

### Crash Report (if applicable)

https://gist.github.com/Pichu6/ed6759a9d11e22ecfdb2fbc4661ea036

### Steps to Reproduce

game crash on start. 
![crash](https://github.com/iPortalTeam/ImmersivePortalsModForForge/assets/141189156/dc1d3eb4-d701-438e-9c0e-aff89bbe2db9)

### What You Expected

the game to start. I believe that forge and game versions where correct. 

### What Happened Instead

game crash at startup 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by PORTALDANCE** [comment]
so whats the solution

**Comment by buildsbricks1** [comment]
ITS BEEN LIKE 4 MONTHS COME ON

**Comment by Nick1st** [comment]
How about not shouting at me?

> ITS BEEN LIKE 4 MONTHS COME ON

**Comment by Nick1st** [comment]
You are missing Cloth Config, which is a required dependency for this mod.
