### ISSUE TITLE
1.20.1?

### ISSUE THREAD

**Issue by myron-obsolete-account** [iPortalTeam/ImmersivePortalsModForForge#138]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

1.20.1

### ImmersivePortals Version

1.20.1?

### Latest Log

N/A

### Crash Report (if applicable)

N/A

### Steps to Reproduce

N/A

### What You Expected

a 1.20.1 port

### What Happened Instead

nothing

### Additional Details

There's 1.20.1 for fabric already but forge has been left behind apparently.

### Please Read and Confirm The Following

- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [x] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Exouxas** [comment]
You can follow the development through the discord server. They're trying to port the 1.20.1 fabric version to forge, and you can check out the progress in the #dev-discussion channel.

**Comment by myron-obsolete-account** [comment]
I don't use discord
