### ISSUE TITLE
Intel Video GUI. Error...

### ISSUE THREAD

**Issue by Sandictoin123** [iPortalTeam/ImmersivePortalsModForForge#139]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

1.18.2

### ImmersivePortals Version

1.18.2

### Latest Log

-

### Crash Report (if applicable)

-

### Steps to Reproduce

-

### What You Expected

I expected it to work...

### What Happened Instead

I got this error...

### Additional Details

-

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by zemuffinnman** [comment]
what error, nothing is attached

**Comment by Nick1st** [comment]
It seems your issue is missing logs as well as a detailed description. Without those things we are not able to help you.

**Comment by Nick1st** [comment]
Closing due to no reply
