### ISSUE TITLE
Game crashs with serene seasons

### ISSUE THREAD

**Issue by agentwolf88** [iPortalTeam/ImmersivePortalsModForForge#14]
### According to your testing, does the issue occur with ONLY Immersive Portals mod?

Yes

### Forge Version

40.1.74

### ImmersivePortals Version

immersive-portals-1.4.9-rc3-mc1.18.2-forge.jar

### Latest Log

https://gist.github.com/agentwolf88/1ce26c86ce5236f71fbf7db449fcadfc

### Crash Report (if applicable)

https://gist.github.com/agentwolf88/57a6ff875e34c50bad32bf2c975e6923

### Steps to Reproduce

Use serene seasons + immersive portals and start the game.

### What You Expected

-----------------------

### What Happened Instead

The game crashs with serene seasons.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Fix [cf57371](https://github.com/iPortalTeam/ImmersivePortalsModForForge/commit/cf57371a6e31e9b2152a3bf2695ddd273ebb5403): Game crashs with serene seasons
This fixes the crash. Note, the mods are still incompatible. There are several rendering issues. Enabling `compatibilityRenderMode` in `imm_ptl-common.toml` fixes most of them.
I'm not going to fix this further, as I'm not interested in debugging closed-source ARR mods. If you want further compat, tell them to provide compat on there side or to provide their source.

**Comment by ghost** [comment]
> 

What do you mean by closed-source ARR? Serene Seasons have github page with Issues and Source

**Comment by Nick1st** [comment]
Yeah, but there GitHub does not contain any source.

**Comment by Sarinsa** [comment]
> > 
> 
> What do you mean by closed-source ARR? Serene Seasons have github page with Issues and Source

Glitchfiend only has open source for TerraBlender iirc. The other mods have closed source, so you must ask for permission to get access

**Comment by Nick1st** [comment]
Only their API code, which on its own is completely useless.

**Comment by Sarinsa** [comment]
Ah oof

**Comment by ghost** [comment]
They said in Discord that you can get access for it
