### ISSUE TITLE
Datapack custom portals not loading

### ISSUE THREAD

**Issue by ArgenNova** [iPortalTeam/ImmersivePortalsModForForge#149]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

43.3.5

### ImmersivePortals Version

2.3.5-mc1.19.2

### Latest Log

https://gist.github.com/ArgenNova/16af933941f6a846da07d91718af6f11#file-latest-log

### Steps to Reproduce

1. Create new world
2. Make special nether portal as defined in example datapack
3. Throw quartz in lava to trigger portal generation

### What You Expected

New nether portal to generate

### What Happened Instead

Nothing

### Additional Details

This was attempted using the example datapack from the immersive portals site: [example_custom_portal_gen.zip](https://github.com/qouteall/ImmersivePortalsMod/raw/1.19/example_custom_portal_gen.zip)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by ArgenNova** [comment]
I forgot to mention: I did make sure that the datapack was added to the world and enabled when I created the world for testing

**Comment by TecmagDiams** [comment]
Just adding a +1 to this as well as confirmation that Nick1st is aware based on conversations from the Discord server the day after this issue was opened.
<img width="659" alt="image" src="https://github.com/iPortalTeam/ImmersivePortalsModForForge/assets/48166478/bee2c64a-0310-4b11-a0ab-2501360085b8">

Not sure if anything else has been found out thus far but I'll be keeping an eye here as this is the one feature that has me ready to do another playthrough of modded Minecraft.

**Comment by ArgenNova** [comment]
I've been looking into this in my own time and actually got it working.
It appears that the issue was registryRegistryKey in CustomPortalGeneration.
It works if you drop the "imm_ptl" namespace from the location.

**Comment by ArgenNova** [comment]
Although I'm not sure if doing this may cause other issues that I didn't find while testing the fix.

**Comment by ArgenNova** [comment]
I do remember stumbling upon a comment from Forge in the MDK about needing to allow non-vanilla registry namespaces in the future. So it may also be fixed in a forge update down the line.

**Comment by Ninzer0** [comment]
what do you mean by "drop the 'imm_ptl' namespace from the location"? i wanna get mine working and i do not understand. an example would help. do you mean like remove the imm_ptl from the generation files? like instead of "imm_ptl:any_dimension" just do "any_dimension"?

**Comment by ArgenNova** [comment]
![Screenshot 2023-12-01 100956](https://github.com/iPortalTeam/ImmersivePortalsModForForge/assets/19187833/4bb5d5ab-61c1-4884-81a9-9115cc9d0180)
This value here.
Found in [this class](https://github.com/iPortalTeam/ImmersivePortalsModForForge/blob/1.19/imm_ptl_core/src/main/java/qouteall/imm_ptl/core/portal/custom_portal_gen/CustomPortalGeneration.java)

**Comment by TecmagDiams** [comment]
> what do you mean by "drop the 'imm_ptl' namespace from the location"? i wanna get mine working and i do not understand. an example would help. do you mean like remove the imm_ptl from the generation files? like instead of "imm_ptl:any_dimension" just do "any_dimension"?

They mean in the file
`imm_ptl_core/src/main/java/qouteall/imm_ptl/core/portal/custom_portal_gen/CustomPortalGeneration.java` to remove `imm_ptl:` from line 52.

Unfortunetly I can't get the project to build and that's mostly from having no know how on building mods haha.

**Comment by Nick1st** [comment]
This has been fixed a while ago. I suppose it's working now? If not, feel free to reopen.
