### ISSUE TITLE
Immersive Portal crashes on Magma server

### ISSUE THREAD

**Issue by Mokonuma** [iPortalTeam/ImmersivePortalsModForForge#15]
### According to your testing, does the issue occur with ONLY Immersive Portals mod?

Yes

### Forge Version

40.1.68

### ImmersivePortals Version

1.4.9-rc3-mc1.18.2

### Latest Log

https://gist.github.com/Mokonuma/b3def0a217f1d18050f5ab3317f2c842

### Steps to Reproduce

When a Magma server is started with the Immersive Portals mod instantly crashes

### What You Expected

The server should just start normally because the forge version of the Magma server should be compatible with the mod, and it works in singleplayer, but not on the server

### What Happened Instead

The Magma server crashes while a Forge server or singleplayer don't

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
I'm not able to support hybrids.

**Comment by Nick1st** [comment]
The server doesn't have permission to access the file. Fix your file permissions.
