### ISSUE TITLE
Crash with create mod on forge version of immersive portals 1.19.2

### ISSUE THREAD

**Issue by luca1808** [iPortalTeam/ImmersivePortalsModForForge#158]
### Is it a mod compatibility issue?

Yes

### If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)

https://www.curseforge.com/minecraft/mc-mods/create

### Minecraft version

1.19.2

### Describe the issue

[latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/14195678/latest.log)

**Comment by Nick1st** [comment]
It seems you're running with many mods. Please try to reproduce the issue with only iPortal and create. Also the log seems to be truncated, please provide a full log.

**Comment by Nick1st** [comment]
No reply was given, probably physics mod
