### ISSUE TITLE
Mod crashing on startup

### ISSUE THREAD

**Issue by manniemarlon** [iPortalTeam/ImmersivePortalsModForForge#164]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

No

### Forge Version

1.16.5-forge-36.2.42

### ImmersivePortals Version

0.17-mc1.16.5

### Latest Log

https://gist.github.com/manniemarlon/e59f863966d1bbbaf7ac768fc70a4d21

### Steps to Reproduce

Step 1 : Install forge
Step 2 : Install a few mods
![explorer_hQ1O1WirHr](https://github.com/iPortalTeam/ImmersivePortalsModForForge/assets/89158570/48960e3e-e8bb-4fcb-a23e-7d69d1cc7f42)
Step 3 : game crash

### What You Expected

I thought everything would work well, just the game launch and then i can play

### What Happened Instead

The game crashed on startup

### Additional Details

I asked for some help in random servers, they say optifine isnt compatible but i remember it working with optifine, 100%

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Try with an older version of / without optifine. Other then that, 1.16 is no longer supported
