### ISSUE TITLE
plz do a 1.20.1 forge, of all the versions to skip, plz!!

### ISSUE THREAD

**Issue by xXFoundationXx** [iPortalTeam/ImmersivePortalsModForForge#171]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

47.3.7

### ImmersivePortals Version

x

### Latest Log

x

### Crash Report (if applicable)

x

### Steps to Reproduce

x

### What You Expected

x

### What Happened Instead

xx

### Additional Details

xx

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Arceus-77** [comment]
Y E S I NEED THIS I WANT TO BUILD AN IMPOSSIBLE HOUSE AND I NEED THIS TO WORK, I WOULD NEED IT FOR A HALLWAY THAT GOES ON FOREVER UNLESS YOU TURN AROUND INFINITE DROPPER AND MORE

**Comment by Nick1st** [comment]
Both of you, please stop spamming our trackers. My reason has been outlined many times before, please just accept it. Either switch to Fabric or update. We do not have the resources to support multiple outdated versions.
