### ISSUE TITLE
Add portal gun and mini-scaled

### ISSUE THREAD

**Issue by Arceus-77** [iPortalTeam/ImmersivePortalsModForForge#173]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

X

### ImmersivePortals Version

X

### Latest Log

X

### Crash Report (if applicable)

X

### Steps to Reproduce

X

### What You Expected

I feel that the portal gun should be available, as well as small rooms.

### What Happened Instead

None of the stuff was there

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Those are separate mods, and I do not have time to port those.
