### ISSUE TITLE
Immersive Engineering causing portal clipping

### ISSUE THREAD

**Issue by pandaguy21** [iPortalTeam/ImmersivePortalsModForForge#177]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

No

### Forge Version

43.4.0

### ImmersivePortals Version

immersive-portals-2.3.7-mc1.19.2-forge.jar

### Latest Log

<script src="https://gist.github.com/pandaguy21/caba3151f41ab05fdbe54e0bb50ab893.js"></script>

### Steps to Reproduce

Use Curseforge to create modpack
Use Forge version 1.19.2
Install Oculus, immersive portals, and immersive engineering
Use Complementary unbound shader
create world
apply shader
create portal

### What You Expected

I expected to noting to happen after adding in immersive engineering after see nothing wrong with using shaders and immersive portals together

### What Happened Instead

Any time I created a portal the visual of the portal would clip through everything including mobs and my character

### Additional Details

![after adding immersive engineering 2](https://github.com/user-attachments/assets/e340dc47-b575-4003-80ee-7096de06adc4)
![after adding immersive engineering 3](https://github.com/user-attachments/assets/f20ac222-4a08-425d-a010-a505082b065e)
![after adding immersive engineering 4](https://github.com/user-attachments/assets/d59f1e66-3448-4983-b87a-2c02a913c6be)
![after adding immersive engineering 5](https://github.com/user-attachments/assets/81121b2a-9efb-48a9-b391-3648fdec44f6)
![After adding immersive engineering](https://github.com/user-attachments/assets/f028c72f-1a1c-4305-9a27-f363d5b37385)
![Before adding immersive engineering 2](https://github.com/user-attachments/assets/fdcd3cf1-168d-4666-9b6a-c7ca52e9b966)
![Before adding immersive engineering](https://github.com/user-attachments/assets/42b60fdc-e373-4840-ba65-b62391806b2f)
The last 2 photos are before adding immersive engineering

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Try disabling stencil buffer usage in Immersive Engineering's config. Also note that this mc version is no longer supported.

**Comment by pandaguy21** [comment]
ah didnt realise it wasnt supported anymore but that did fix it thank you
