### ISSUE TITLE
Please support my cracked client!!! (~~Billions of command sticks~~)

### ISSUE THREAD

**Issue by Fr4Ckt3r** [iPortalTeam/ImmersivePortalsModForForge#19]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes, it seems.
Except the fact that im using forge.

### Describe the issue

video explains it

https://user-images.githubusercontent.com/50457706/189477664-ccd24751-96ce-49f8-93d0-45ad3c9b24f8.mp4

**Comment by qouteall** [comment]
You said that this issue does not occur with only immptl. Can you find which mod caused this issue?

**Comment by Fr4Ckt3r** [comment]
> You said that this issue does not occur with only immptl. Can you find which mod caused this issue?

Seems to happen even without other mods... 1.18.2 Forge, no optifine, no rubidium and any other optimization shtuff.
There are only one duplicate for every stick however. Seems that other mods somehow makes them multiplicate.
UPD: log
[n.txt](https://github.com/iPortalTeam/ImmersivePortalsMod/files/9540226/n.txt)

**Comment by Nick1st** [comment]
Please proof that you own Minecraft. I won't support pirated versions of the game.

**Comment by Fr4Ckt3r** [comment]
> Please proof that you own Minecraft. I won't support pirated versions of the game.

welp, no proof is coming then, i'm not supporting microsoft now nor will support them ever.
second, i can't buy game in any way, my physical location dissalows me to.
third, game costs too much. 
notch himself told to pirate it if you can't afford it.

i don't see what is the issue with that, but k

**Comment by Nick1st** [comment]
The issue is it's illegal and pirating should not be supported.

**Comment by ScoutTheSaneless** [comment]
i can actually vouch for this issue's legitimacy on a fully purchased and migrated account of the game. If you want proof that my MC acc is legit, my current user as of writing this is "ChaosDog"

**Comment by Fr4Ckt3r** [comment]
> i can actually vouch for this issue's legitimacy on a fully purchased and migrated account of the game. If you want proof that my MC acc is legit, my current user as of writing this is "ChaosDog"

and here comes the proof



> The issue is it's illegal and pirating should not be supported.

you consider supporting your own mod illegal?

**Comment by Nick1st** [comment]
No, pirating the game is illegal. Modding is not. But you can get problems if you support cracked clients. And cracked clients also cause modders to loose revenue, so no support for them.

**Comment by Nick1st** [comment]
@ChaosDogG please send a log, thanks.

**Comment by Fr4Ckt3r** [comment]
> No, pirating the game is illegal. Modding is not. But you can get problems if you support cracked clients. And cracked clients also cause modders to loose revenue, so no support for them.

show me an example of a modder who got in jail or got a fine for supporting somebody (no, not for political views)
thus, i'm not asking you to pirate the game yourself and you actually should have the right to do so, if you bought it already.

**Comment by Nick1st** [comment]
@Fr4Ckt3r 
This is enough, stop it.

**Comment by Fr4Ckt3r** [comment]
welp, fine.
still, people like haubna do paid mods like physics mod pro and this is illegal by minecraft eula, yet nobody didn't do a thing about that.

**Comment by Nick1st** [comment]
@qouteall please just ban @Fr4Ckt3r from the organisation, this is leading nowhere
