### ISSUE TITLE
Overabundance of Command Sticks

### ISSUE THREAD

**Issue by ScoutTheSaneless** [iPortalTeam/ImmersivePortalsModForForge#22]
### According to your testing, does the issue occur with ONLY Immersive Portals mod?

Yes

### Forge Version

40.1.80

### ImmersivePortals Version

1.4.9-rc3-mc1.18.2

### Latest Log

https://gist.github.com/ChaosDogG/2f7a49b9391834e3fc846512cb84bafe

### Steps to Reproduce

1. Load game
2. Go to misc tab where they normally belong
3. Discover a TON of excess sticks

### What You Expected

one stick per command as intended

### What Happened Instead

somehow there had to have been a hiccup in the code that told the game to duplicate the sticks

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by ScoutTheSaneless** [comment]
Im creating this issue mostly because the original one got locked and i couldnt post my log as requested

**Comment by Nick1st** [comment]
Yeah, thanks for doing this 🙏. I wasn't able as I was on mobile.

**Comment by Nick1st** [comment]
Just to make sure, this is reproducible in the latest version?

**Comment by Nick1st** [comment]
Please try with the newest version 1.4.11
