### ISSUE TITLE
Sticks Bug

### ISSUE THREAD

**Issue by Flipss8** [iPortalTeam/ImmersivePortalsModForForge#23]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

No

### Describe the issue

There is a huge bug running on my version of Inmersive portals in forge.  In first place, there are a lot of sticks that dont work. They are the ones that rotate the portal (X, Y, Z), the unbreakable portal, the fuse view, the "pos teleport, pos adjust", the one that dont render yourself, the one that ables and disables the isometric view, the ones that accelerat (and desacelerate), the ones that change your scale and the one with the wiki. Also in the creative page where the sticks and portals appears, the sticks multiplicate. This error also appears when I stop using mods.
Forge version is 40.1.76 running on 1.18.2. 
The version of IP is the last one. 
The mods active are Security Craft (1.9.31), Mr Crayfish Furniture, Chipped, Framed Blocks, Geckolib, Macaw Doors, MouseTweaks, Mowzies Mob, Secret Rooms and Selene.
I am not using any kind of shaders, but I tried to  use Optifine in that same version.
![Sticks multiplicate (they are a lot more of them)](https://user-images.githubusercontent.com/113394731/189773155-191d9234-38d4-4aa4-9048-5f090f6d3300.png)
[latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/9552298/latest.log)

### Post the log here

```shell
I upload the log in the message because it was too long or uploading it.
```

**Comment by Nick1st** [comment]
Thanks for the report. I suppose this is easy to fix, though I need a bit of extra information. When using the broken sticks, what happens? Nothing? An error message in the chat? Something else?

Also, I know this is quite some work, but could you please list all broken command sticks so I don't forget to fix one.

**Comment by Nick1st** [comment]
Immersive Portals Version is `1.4.10-mc1.18.2`. (Note for the future: Please write out the version. Latest is not static and as such quite useless.)

**Comment by Nick1st** [comment]
Yeah, I found the cause will fix it soonTM.

**Comment by Fr4Ckt3r** [comment]
> Yeah, I found the cause will fix it soonTM.

so what, was it that hard to check the issue instead of just blaming me?

**Comment by Flipss8** [comment]
List of Sticks that dont work:

- Apply rotation along X 15 degrees (portal rotate_portal_rotation_along X 15)
- Apply rotation along Y 15 degrees (portal rotate_portal_rotation_along Y 15)
- Apply rotation along Z 15 degrees (portal rotate_portal_rotation_along Z 15)
- Make the portal unbreakable (portal set_portal_nbt {unbrekeable:true})
- Make the portal fuse view (portal set_portal_nbt {fuseView:true})
- Enable Post-Teleport Pos Adjustment (portal set_portal_nbt {adjustPositionAfterTeleport:true})
- Make the portal to not render yourself (portal set_portal_nbt {doRenderPlayer:false})
- Enable isometric view for you (portal debug isometric_enable 50)
- Disable isometric view for you (portal debug isometric_disable)
- Accelerate 50 (portal debug accelerate 50)
- Accelerate 200 (portal debug accelerate 200)
- Reverse accelerate 200 (portal debug accelerate -50)
- Check IP Wiki (portal wiki)

I couldnt try the gravity changing stick and scale stick because I didnt downloaded the mods.

**Comment by Nick1st** [comment]
Thank you very much 🙏

**Comment by Nick1st** [comment]
This will actually take longer as I thought, as this requires me to rewrite at least one protocol completely, also containing it's countless codecs...

**Comment by Nick1st** [comment]
I suggest usage of commands for now and then reloading the world to manually sync the portals

**Comment by Nick1st** [comment]
Please try with the newest version 1.4.11
