### ISSUE TITLE
[Bug] Ars Nouveau

### ISSUE THREAD

**Issue by Aegael** [iPortalTeam/ImmersivePortalsModForForge#24]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

Yes

### Describe the issue

Playing on the 1.18.2 forge version -- using only Ars Nouveau with Immersive Portals, and then saving a game, then reloading the save will cause the mana bar from Ars Nouveau to appear empty and stuck on the screen permanently.

**Comment by Nick1st** [comment]
Please edit your description to contain all information contained [here](https://github.com/iPortalTeam/ImmersivePortalsModForForge/issues/new?assignees=&labels=bug&template=bug-report.yml). 

@Aegael

**Comment by Nick1st** [comment]
Closed due to missing response. If any1 can reproduce this in a newer version, feel free to open a new issue.
