### ISSUE TITLE
Not Compatible with Twilight forest?

### ISSUE THREAD

**Issue by firestorm2039** [iPortalTeam/ImmersivePortalsModForForge#26]
back on 1.16.5 i used to have both this mod and twilight forest installed, but as i have upgraded to 1.18.2 it says they are not compatible?
When i die and respawn, the screen turn white after a seconds, i am forced to save and exit, then load the game up again to fix this (until i die next).

due to this i have had to remove this mod which has fixed the issue (my son prefers twilight forest).

is there a way you can make it compatible again? as i hate the loading screen on end/nether portals lol

**Comment by Nick1st** [comment]
Nothing (I know of) to do on this end. Sorry.

**Comment by TelepathicGrunt** [comment]
@Nick1st can you explain in more detail what the issue is? Have you made an issue report to twilight forest so they even know of the issue? 

From what it sounds like, the TF devs had no idea about this and only saw a user with the chat message talking about the incompat. And currently think the issue is on immersive portal’s side for being unable to be compat with another mod’s dimension. 

Basically, more info and communication is needed of what the actual issue is so that someone can actually act upon it.

**Comment by qouteall** [comment]
Fristly, ImmPtl does not intentionally break anything of twilight forest. And ImmPtl is compatible with most Fabric dimension mods. So there is something special with twilight forest. It's not an issue of only ImmPtl's side.

Last time I tested ImmPtl with twilight forest and the chunk data packets of the twilight forest dimension has deserialization error. I don't know what caused the packet deserialization error. I roughly checked twilight forest's mixins and asm scripts and did not see anyting related to chunk data packets. Maybe I missed something.

ImmPtl wraps some packets as redirected packet. The redirected packet contains the dimension id and packet type id and the packet being wrapped.

**Comment by qouteall** [comment]
https://github.com/iPortalTeam/ImmersivePortalsMod/issues/1133

**Comment by Nick1st** [comment]
@TelepathicGrunt I already mentioned that this issue also exists in the forge version on the original fabric issue report, in hope they transfer the issue.
I'm going to create a new issue on their Forge Project.

**Comment by firestorm2039** [comment]
> @Nick1st can you explain in more detail what the issue is? Have you made an issue report to twilight forest so they even know of the issue?
> 
> From what it sounds like, the TF devs had no idea about this and only saw a user with the chat message talking about the incompat. And currently think the issue is on immersive portal’s side for being unable to be compat with another mod’s dimension.
> 
> Basically, more info and communication is needed of what the actual issue is so that someone can actually act upon it.

i did put a comment in their comments section, but i know nothing about modding, so i cant say what the issue could be, just that there is an issue.
i did not create a "report issue" post, i think it was asking to much info that i didnt know, or something.

i use Forge Versions, never used fabric.

**Comment by Nick1st** [comment]
@TelepathicGrunt @qouteall @firestorm2039 
From now on, this will be tracked in #36, as that issue provides way more details.
