### ISSUE TITLE
Rendering Issues with Mekanism and some other mods

### ISSUE THREAD

**Issue by Gamephantom** [iPortalTeam/ImmersivePortalsModForForge#27]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

40.1.80

### ImmersivePortals Version

1.4.9-mc1.18.2

### Latest Log

https://gist.github.com/Gamephantom/973ad2c0e82c7514f3eaf310002f12a1

### Steps to Reproduce

1. Build Mekanism mechanics
2. Enter a portal
3. Save And Exit
4. Reenter the world

### What You Expected

Correct rendering of the mekanism mechanics.

### What Happened Instead

Incorrect rendering like in the screenshot.
![2022-09-23_20 33 30](https://user-images.githubusercontent.com/1436165/192036111-bf605297-6430-41ee-abf9-2da41ae52df4.png)

### Additional Details

It also occurs on other mods like Applied Energistics 2, Ender Tanks etc.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by qouteall** [comment]
I used to fix this by making the model data system per-dimension https://github.com/qouteall/ImmersivePortalsModForForge/blob/1.16/src/main/java/com/qouteall/forge_model_data_fix/ForgeModelDataManagerPerWorld.java

https://github.com/qouteall/ImmersivePortalsModForForge/blob/1.16/src/main/java/com/qouteall/hiding_in_the_bushes/mixin/client/MixinForgeModelDataManager.java

**Comment by Gamephantom** [comment]
@qouteall I ported your fix to this version and it worked :)

I created a Pull Request for @Nick1st

**Comment by Nick1st** [comment]
Yeah, I remember having thought about it but then I forgot about it. Thanks

**Comment by Nick1st** [comment]
This might also be the cause of #11

**Comment by Caseyxx** [comment]
> @qouteall I ported your fix to this version and it worked :)
> 
> I created a Pull Request for @Nick1st

where to did you port this too? would like to do this myself but no idea what i'm doing

**Comment by Nick1st** [comment]
Just build the latest commit

**Comment by Caseyxx** [comment]
> Just build the latest commit

what do u mean by that? when it comes to mods i'm not that experienced xD
