### ISSUE TITLE
Incompatibility with vivecraft 1.18.2

### ISSUE THREAD

**Issue by MarkeR2005** [iPortalTeam/ImmersivePortalsModForForge#28]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

40.1.51

### ImmersivePortals Version

1.4.11-mc1.18.2

### Latest Log

https://gist.github.com/MarkeR2005/d11f7466873716931939ff24abfaf5fc

### Crash Report (if applicable)

https://gist.github.com/MarkeR2005/8e6add4eff3d54bd4a9e85e73f1e90d7

### Steps to Reproduce

1. Download and install vivecraft 1.18.2 with forge.
2. Download and put in mods folder immersive portals (forge)
3. Launch the game and try to create a new world (didn't tested in previously created ones).
4. Get the crash report.

### What You Expected

I expected any type of expirience even with bugs or major issues.

### What Happened Instead

Game immediatly crashed when I tried to enter the world.

### Additional Details

Vivecraft uses optifine as a core.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
I'm sorry, but I can not support Optifine.
