### ISSUE TITLE
Adaptive portal config option doesn't work.

### ISSUE THREAD

**Issue by CowChunks** [iPortalTeam/ImmersivePortalsModForForge#3]
### According to your testing, does the issue occur with ONLY Immersive Portals mod?

Yes

### Forge Version

40.1.73

### ImmersivePortals Version

immersive-portals-1.4.9-mc1.18.2-forge

### Latest Log

https://gist.github.com/CowChunks/96d0b2e3f7413e69e4b700da33f6dd61

### Steps to Reproduce

Step 1: Enable Adaptive portal mode in config for the nether portal.
Step 2: Attempt to create a nether portal.
The portal will sit in a animation and say "Existing Frame cannot Be Found, Generating New Frame." or "Finding Existing Frame"

### What You Expected

For the adaptive portal config to work.

### What Happened Instead

The portal wouldn't open

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
I can't reproduce this with nether portals.
Also, your log does only show datapack portal generation attempts. Please send a log with only one nether portal lightening attempt.
