### ISSUE TITLE
Crash when making overworld

### ISSUE THREAD

**Issue by Xplodin** [iPortalTeam/ImmersivePortalsModForForge#30]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

40.1.80

### ImmersivePortals Version

1.4.11-1.18.2

### Latest Log

https://gist.github.com/Xplodin/ab71c1a2de785092088dea9b925e7659

### Crash Report (if applicable)

https://gist.github.com/Xplodin/17c8a2047ae30eb823d5ea2403c4ad79

### Steps to Reproduce

1. install immersive portals forge alongside lootr
2. crash when making a sp world

### What You Expected

to not crash when creating a world. creating a world. etc

### What Happened Instead

crash to main menu, then hardlock freezing crash after trying again

### Additional Details

I think its lootr

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
It's not lootr. Please do a binary search to help diagnose this issue:
```
The binary search is a way of finding a faulty thing among a lot of other things, without having to remove the things one-by-one.

This is useful for finding a broken mod among hundreds of mods, without having to spend time testing the mods one-by-one.

The procedure is simple:
1. Remove half of the existing mods, and put them aside.
2. Run the game.
3. Does the issue still exist?
If YES: Repeat from step 1 with the current mods.
If NO: Swap out the current mods with the ones set aside, and repeat from step 1.
4. Repeat this process until the problematic mod/s have been found.
```

**Comment by Nick1st** [comment]
Closed due to missing response. If any1 can reproduce this in a newer version, feel free to open a new issue.
