### ISSUE TITLE
Infinite loading chunks if using a vanilla nether portal, close to the locations of immersive portals.

### ISSUE THREAD

**Issue by LewdSenpaido** [iPortalTeam/ImmersivePortalsModForForge#35]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

No

### Forge Version

40.1.80

### ImmersivePortals Version

1.4.12-mc.1.18.2

### Latest Log

n/a

### Steps to Reproduce

1. Made an immersive portal that connects my house to the nether.
2. Make vanilla Nether portals in the same chunk on each overworld and nether, for your trains ofc.
3. Go through the vanilla nether portal.
4. Go Back Through again.
5. Sit and wait for chunks to load indefinitely or /kick yourself, or kill game.

### What You Expected

Do the normal portal thing!

### What Happened Instead

You get a infinite loading chunks glitch till relogging. Also another thing to note is if you do this and return to the nether/overworld in a different chunk, the chunk that the immersive portal and nether portal is on is a big void in the world until relogging, stepping into it will "capture" you or make you invisible until Relogging (Dont think it makes you invis to other players.)

### Additional Details

Also in the server command prompts say [15:10:08] [Server thread/INFO] [Portal/]: ignored dubious move packet minecraft:overworld 29.119782911208716 64.58096308195604 28.616150955526063 270.5 201.57766878909024 228.61615173038643 Removed my immersive portal from this locations in both the nether and overworld and works again.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Please provide a log.

**Comment by Nick1st** [comment]
@LewdSenpaido without a log I can't diagnose this
