### ISSUE TITLE
Immersive Portals Core has failed to load correctly!

### ISSUE THREAD

**Issue by iltan987** [iPortalTeam/ImmersivePortalsModForForge#37]
Immersive Portals Core (imm_ptl_core) has failed to load correctly!
Minecraft Version: 1.18.2 with Forge 40.0.24
Windows 10 version 21H2 Build 19044.2130
(and I am using TLauncher)
Please fix.
![image](https://user-images.githubusercontent.com/89255395/196042126-e71a3a24-8496-4d1b-aafa-95bfe8dc1342.png)

Log file: [crash-2022-10-16_17.46.11-fml.txt](https://github.com/iPortalTeam/ImmersivePortalsModForForge/files/9794920/crash-2022-10-16_17.46.11-fml.txt)

**Comment by Nick1st** [comment]
Can you prove that you own the game?

**Comment by Nick1st** [comment]
Also this does not provide sufficient information.
