### ISSUE TITLE
1.12.2 please

### ISSUE THREAD

**Issue by BrianTheMint** [iPortalTeam/ImmersivePortalsModForForge#38]
most mods are available around the 1.12.2 version, id like to see this

**Comment by Lolothepro** [comment]
https://howoldisminecraft1122.today/

**Comment by RemagOfficial** [comment]
@OrlandB2045 won't happen

**Comment by DarknessOverlord** [comment]
Its still unavailable on 1.12.2?

**Comment by ImSpaceLover** [comment]
No, and it never will be

**Comment by DarknessOverlord** [comment]
> No, and it never will be

Cool
