### ISSUE TITLE
Datapack portals do not open

### ISSUE THREAD

**Issue by CowChunks** [iPortalTeam/ImmersivePortalsModForForge#4]
### According to your testing, does the issue occur with ONLY Immersive Portals mod?

Yes

### Forge Version

40.1.73

### ImmersivePortals Version

immersive-portals-1.4.9-mc1.18.2-forge

### Latest Log

https://gist.github.com/CowChunks/e8d387d32e488404388d90e94a0f9db1

### Steps to Reproduce

1. Use a datapack for custom portals
2. open a portal with what the Datapack has set for a block type 

### What You Expected

For the portals data pack portals to work

### What Happened Instead

The portals lit up but didn't open and had the message "Existing Frame cannot Be Found, Generating New Frame." 

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Ok, thanks for the report! 
This has most likely the same cause as #3

**Comment by Nick1st** [comment]
I think I found the cause. However, just to make sure, can you please send me the datapack you tried to use?
