### ISSUE TITLE
Shaders breaks when two portals are loaded in same dimension at same time.

### ISSUE THREAD

**Issue by TofuHell** [iPortalTeam/ImmersivePortalsModForForge#41]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

No

### Forge Version

40.1.68

### ImmersivePortals Version

1.4.12-mc1.18.2

### Latest Log

https://gist.github.com/TofuHell/3fef92da394c7619c1021eaa4e2bd562

### Steps to Reproduce

1, load oculus shaders and immersive portals.
2, make two portals within the same render distance, effects better if pointsing towards eachother
3, turn on any shader pack
4, view

### What You Expected

I assume the shaders to ignore the portals or interact normally with the portals as if they are surface.

### What Happened Instead

The shaders i assune kept looping into eachother creating odd visual errors 

### Additional Details

Video of the error
https://youtu.be/klqhm6GmKgM
I also have images if need be.

shaders i used were Complimentary Shaders and all the versions of SEUS shaders

If you need anything else at all please tell me.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by TofuHell** [comment]
I Tested this with only Oculus and Rubidium and Immersive portals installed and same issue. im gonna send its error log

https://gist.github.com/TofuHell/fc9ddc97de958f26756bb55b144230c8 

this was with Forge 40.1.0 and Immersive Portals 1.4.12-mc1.18.2

**Comment by Nick1st** [comment]
Did you test it with a different shader?

**Comment by TofuHell** [comment]
yes all big shaders (complimentary, seus, sildurs, BSL,  etc) experience this problem unfortunately

**Comment by Nick1st** [comment]
I can't reproduce this. But SEUS / Sildurs are quite known for causing issues with mods in general. Complementary / BSL should work, I test on both of these shaders. But as I said, I'm unable to reproduce this. Can you please tell me your

- Java Version and Vendor
- OS and Arch

And try again with the latest versions of all mods involved.

**Comment by TofuHell** [comment]
im sorry for being so late. The issue was something with my graphics card drivers, i had recently upgraded. I'm sorry for wasting your time.

**Comment by Nick1st** [comment]
No problem, glad you resolved it.
