### ISSUE TITLE
1.19.2...?

### ISSUE THREAD

**Issue by mrthethatone** [iPortalTeam/ImmersivePortalsModForForge#43]
Is there going to be a version for 1.19.2 anytime soon? Because the main fabric one is on 1.19 and this version is being updated still, so will there be a version for 1.19?

**Comment by SalTeyJek004** [comment]
Eventually, the person maintaining the forge version has asked people to stop asking

**Comment by SlimeAdventure1** [comment]
I want this mod to be backported to 1.16.5 and 1.17.1 because i'm waiting for people to have it, not trying to waste their time with using Fabric version of that. even it is Forge.
