### ISSUE TITLE
Add for forge 1.19

### ISSUE THREAD

**Issue by An-m1654** [iPortalTeam/ImmersivePortalsModForForge#47]
Please add forge 1.19 version or I will make it.
   vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
>(Also please please please give me premission)<
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by qouteall** [comment]
Thanks for your intention of contributing. You can already contribute and open an pull request. No special permission needed for contribution.

**Comment by Nick1st** [comment]
Feel free to do so

**Comment by An-m1654** [comment]
i'll try

> Feel free to do so

**Comment by NextdoorPsycho** [comment]
Being that you have not answered me in DM, and seem like you are actively ignoring me, im doing it myself.
https://github.com/NextdoorPsycho/ImmersivePortalsMod-1.19-FORGE

**Comment by NextdoorPsycho** [comment]
Ill Pr it when im done. any help is open but me and a buddy are doing it, gimme a few days

**Comment by An-m1654** [comment]
my timezone and yours are different so I cannot answer in the same time.

**Comment by An-m1654** [comment]
and also my gradle isn’t working

**Comment by An-m1654** [comment]
and also I would love to do it with you.

**Comment by NextdoorPsycho** [comment]
> and also I would love to do it with you.

you are welcome to make any Pr's into my project, im more of a Bukkit / forge guy, and my friend is a fabric / forge guy. Give me your Discord and i can message you

`⋈-NextdoorPsycho-⋈#0001`

**Comment by Nick1st** [comment]
> Being that you have not answered me in DM, and seem like you are actively ignoring me, im doing it myself. https://github.com/NextdoorPsycho/ImmersivePortalsMod-1.19-FORGE

"actively ignoring me" ... just to inform you, I got your DM a bit over 27 hours ago (I think, at least that's the timestamp I got from the message). I need sleep, I have other projects that **need** to be updated. I switched OS, didn't have a working installation of my IDE and enough other problems to solve. Although I have my DMs open that doesn't mean I'm having a daily look at them. 
As I already stated, everyone can contribute to the project. 
Ok, that's enough about my personal situation.

Before actively porting I'd suggest making Pull Request to the Fabric Repo, strictly splitting the fabric code into it's own package. Saves you a few headaches, especially if you plan on doing long-term upgrades. The current code is just a mess to port and merge. That's something I already discussed with quoteall. There have been some heavy refactors (mostly the animation system) going on lately. Also there were some heavy MC (and especially Forge) changes (Command Nodes, MessageBuilder, _Rendering_) afaik. So I'm not sure what the best starting point for a port is. The way I'm currently planning to do it is using the current Fabric 1.19 branch and cherry-picking most Forge 1.18 changes to it.

**Comment by Nick1st** [comment]
Ok, so everyone interested in contributing and helping to maintain the Forge version should use https://github.com/iPortalTeam/ImmersivePortalsModForForge/discussions to do so. Post about what parts you plan to update, or what code you want to document. (This would greatly increase maintainability.) Also post about problems you run into, so others can help you. I'm always open for Pull Requests :grinning:
