### ISSUE TITLE
Cannot invoke "net.minecraft.resources.ResourceKey.m_135782_()" because "dimension" is null

### ISSUE THREAD

**Issue by MehdiPG** [iPortalTeam/ImmersivePortalsModForForge#48]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

40.1.84

### ImmersivePortals Version

1.4.12-mc1.18.2

### Latest Log

https://pastebin.com/raw/xarkjxry

### Steps to Reproduce

1. Install the mod in the server
2. Join the game
3. instantly kicks you out of the game

### What You Expected

I expected to join the server

### What Happened Instead

When you join, it says loading world and then it kicks you

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [ ] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
This report does not meet any requirements. Please share the full log.

**Comment by MehdiPG** [comment]
Ok sorry.
[latest.log](https://github.com/iPortalTeam/ImmersivePortalsModForForge/files/9998163/latest.log)

**Comment by MehdiPG** [comment]
I have tested it in another server without any mods and it shows the same error

**Comment by Nick1st** [comment]
Please send a new log if there are still problems. The error you get is normal and only happens in the last tick of a server before it exists.

**Comment by VeroFess** [comment]
This problem is not caused by [ImmersivePortalsModForForge](https://github.com/iPortalTeam/ImmersivePortalsModForForge), an attempt has been made in another project to fix it. see https://github.com/IzzelAliz/Arclight/pull/862

**Comment by hxgohxrr** [comment]
Have used Magma right of other hybrid server?

**Comment by Nick1st** [comment]
Using magma is not Supported.
