### ISSUE TITLE
Auto Leveling mod capability is not being synced to client

### ISSUE THREAD

**Issue by Daripher** [iPortalTeam/ImmersivePortalsModForForge#54]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

No

### Forge Version

40.1.85

### ImmersivePortals Version

1.4.12-mc1.18.2

### Latest Log

https://gist.github.com/Daripher/2449e903ee02d6a32d5dd820672f45a9

### Steps to Reproduce

1. Summon a zombie, it should be level 1.
2. Teleport at least 200 blocks away from spawn.
3. Summon a zombie again, it will still be level 1.

### What You Expected

By default, monsters should gain 1 level for every 100 blocks traveled from spawn.

### What Happened Instead

Monsters do gain levels, however this data is not being synced. Visual level of every monster is 1.

### Additional Details

Mod that is being broken:
  CurseForge: https://www.curseforge.com/minecraft/mc-mods/auto-leveling.
  GitHub: https://github.com/Daripher/Auto-Leveling

I've also tested that with Jade mod to see if monsters gain additional health with levels and they do. Which means this is just synchronization issue.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
The capability is synced through a custom package, isn't it?

**Comment by Daripher** [comment]
> The capability is synced through a custom package, isn't it?

What do you mean?
It is a custom capability and it is synced through mod. But something breaks when I'm installing Immersive Portals.

**Comment by Daripher** [comment]
After some more tests I've figured out that packets are not even being sent. I'm using **net.minecraftforge.event.entity.player.PlayerEvent.StartTracking** event to detect when mobs data needs to be synced and looks like this event is not being fired.

**Comment by Daripher** [comment]
I'm pretty sure this issue breaks any mod that uses **PlayerEvent.StartTracking** event, because it is never being called.
