### ISSUE TITLE
Minecraft crashes while starting on the 1.16.5 versions 0.17 and 0.16

### ISSUE THREAD

**Issue by chance-nb** [iPortalTeam/ImmersivePortalsModForForge#57]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

36.2.34

### ImmersivePortals Version

0.17-mc1.16.5 and 0.16-mc.1.16.5

### Latest Log

https://gist.github.com/miel8/eeb53781791250b60e364d737a93d63a

### Crash Report (if applicable)

It is a crash, but no report was created

### Steps to Reproduce

1. Start Minecraft
2. It will crash while starting

### What You Expected

Minecraft starting

### What Happened Instead

Minecraft crashed

### Additional Details

I am running a Linux (Ubuntu-based) system and use MultiMC for launching the game.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by chance-nb** [comment]
It randomly decided to work again

**Comment by qouteall** [comment]
The newer fabric loader has newer version of Mixin that does not allow some of the mixin usages. I am planning to fix that.

**Comment by qouteall** [comment]
Tested that the latest version in 1.16.5 works with the latest Fabric loader.
