### ISSUE TITLE
Crash on using Agricraft Seed analyzer

### ISSUE THREAD

**Issue by Haerar** [iPortalTeam/ImmersivePortalsModForForge#59]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

No

### Forge Version

40.1.86

### ImmersivePortals Version

1.4.12-mc1.18.2

### Latest Log

https://gist.github.com/Haerar/1f25586e44a8b1577ec6b56ef04350af

### Crash Report (if applicable)

https://gist.github.com/Haerar/61b0477c3475ec89f44cd68708f1a4ad

### Steps to Reproduce

With Immersive Portals installed alongside Agricraft, try to use the seed analyzer with or without seeds placed in it.

No portal needs to be nearby or even generated/activated

### What You Expected

Viewing of the seed (or lack thereof) via the Agricraft seed analyzer - this zooms in the player's view at an angle, and if a seed is present, renders a double-helix on-screen which can be scrolled through to rotate and analyze the genetics of the seed.

### What Happened Instead

CTD with appropriate error message:

`The game crashed whilst unexpected error
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.renderer.entity.EntityRenderer.m_114505_(net.minecraft.world.entity.Entity, float)" because the return value of "net.minecraft.client.renderer.entity.EntityRenderDispatcher.m_114382_(net.minecraft.world.entity.Entity)" is null`

### Additional Details

This is clearly an edge-case but agricraft has been a reasonably popular mod for a while - so low priority but probably worth looking at.

I suspect it's the rendering of the aforementioned double-helix that's causing the crash, given the log stating a "null entity" that's trying to be (pre)rendered for immersive portals to use at qouteall.imm_ptl.core.render.context_management.RenderStates.updatePreRenderInfo

If an entity is null for this function call (updatePreRenderInfo), could it not be gracefully handled by simply returning and not attempting to render? Or does this have some knock-on chain effect down the line? Sorry, Java coder here, I think about these things too much.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [x] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Can you please send a log with only Agricraft and  ImmPtl loaded?

**Comment by Nox13last** [comment]
Looks like OP's dead. Mind if I butt in?

**Comment by Nick1st** [comment]
Superseded by #132
