### ISSUE TITLE
[Bug] Issue with Connectivity

### ISSUE THREAD

**Issue by Dezzixr** [iPortalTeam/ImmersivePortalsModForForge#60]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

No

### Forge Version

40.1.86

### ImmersivePortals Version

1.14.12-mc1.18.2

### Latest Log

https://gist.github.com/Dezzixr/b0a32e1c32c2626a93d1dfbf938b30c7

### Steps to Reproduce

Have both Connectivity and Immersive Portals installed, log in to server and get the error.

### What You Expected

I expected both mods to be compatible-- And to be able to log in fine.

### What Happened Instead

Both Immersive Portals and Connectivity are installed. Connectivity is CRUCIAL because it helps me get rid of "payload is larger than..." issues in a VERY bloated modpack.

When attempting to login to my server with both mods, i am faced with the "Internal exception: Java.Lang.nullPointerException: Cannot invoke “net.minecraft.network.protocol.Packet.m5797(net.minecraft.network.PacketListener)” because “packet” is null" error.

### Additional Details

![image](https://user-images.githubusercontent.com/72324699/208418926-d4544e7f-5e07-46a4-b610-9e04baf0c44b.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Tracked in #21
