### ISSUE TITLE
Failed to sent packet

### ISSUE THREAD

**Issue by UrbanSide** [iPortalTeam/ImmersivePortalsModForForge#62]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

40.1.86

### ImmersivePortals Version

1.4.12-mc1.18.2

### Latest Log

https://gist.github.com/UrbanSide/621d74283b0a289eda4bc7929f23919b

### Steps to Reproduce

Started connecting to the server
Got this error

### What You Expected

I should have connected to the server :D

### What Happened Instead

I can't connect to the server due to this error

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.

**Comment by Nick1st** [comment]
Tracked in #21
