### ISSUE TITLE
Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot invoke "net.minecraft.resources.ResourceKey.m_135782_()" because "dimension" is null

### ISSUE THREAD

**Issue by hxgohxrr** [iPortalTeam/ImmersivePortalsModForForge#64]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

40.1.86

### ImmersivePortals Version

1.4.12 1.18.2 Forge

### Latest Log

https://gist.github.com/NullGang/2cec1141a8a78221fe7834ab9f9f88dc

### Steps to Reproduce

1. Created a portal
2. Linked it
3. Pass through 2 times
4. Crash

### What You Expected

I expect that it don't crashes.

### What Happened Instead

It crashed my server and kicked me.

### Additional Details

I used Rubidium (A fork of CaffeineMC's "Sodium" for forge) and used Oculus (A fork of Iris for forge).
I don't know if this mods are the problems.
I used Magma

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
...
1. Full Log.
2. Crash report.
3. Don't tick `I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.` if you do. 
4. Hybrids are not supported and never will be. **They** are the problem.

**Comment by hxgohxrr** [comment]
The problem is oculus. the mod
