### ISSUE TITLE
Game stuck on loading dimension screen when an immersive portal and a vanilla one are close to each other.

### ISSUE THREAD

**Issue by Blugori** [iPortalTeam/ImmersivePortalsModForForge#66]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

40.2.0

### ImmersivePortals Version

1.4.13

### Latest Log

https://gist.github.com/Blugori/a3a48ec512f42d18fdb067de5e50e8ed

### Steps to Reproduce

1. Build a vanilla portal 
2. Pass threw it so it generates in the nether
3. Build an immersive portal 
4. Pass threw the immersive one, everything work fine
5. Pass threw the vanilla portal, the game get stuck on the loading dimension screen

### What You Expected

I expected the vanilla portal to work the same way as it worked before building the immersive portal next to it

### What Happened Instead

I couldn't use the vanilla portal after building the immersive one, because if I pass threw it I get stuck on the loading dimension screen 

### Additional Details

(I didn't really confirmed that this happend on fabric, but I was told on discord I could check the condition, sorry for the inconvenience)

How I built my portals :

![2023-01-08_14 28 34](https://user-images.githubusercontent.com/66573974/211198841-2ad938e0-a3a9-49f3-abb7-91149a6c645c.png)
![2023-01-08_14 28 40](https://user-images.githubusercontent.com/66573974/211198844-a581c6ce-8f31-41aa-a629-0af913e8538b.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Blugori** [comment]
![image](https://user-images.githubusercontent.com/66573974/233771176-926e23d3-54c9-497c-b5a0-79b9e24a885f.png)
![image](https://user-images.githubusercontent.com/66573974/233771185-230c607e-a84c-4615-b4db-aa25b7b00183.png)

Tested with immersive portals 1.4.16

**Comment by Blugori** [comment]
The weirdest things are that even if the terrain is loading, I can hear near mobs, weather, etc

**Comment by KellCon** [comment]
is it going to be fixed?
