### ISSUE TITLE
Dimension stick not working*

### ISSUE THREAD

**Issue by ElArsyi** [iPortalTeam/ImmersivePortalsModForForge#67]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

No

### Forge Version

1.18.2?*

### ImmersivePortals Version

1.4.12 mc 1.18.2*

### Latest Log

idk*

### Crash Report (if applicable)

idk*

### Steps to Reproduce

1. it appears for no reason*
2. this bug is common for me*

### What You Expected

dimension stick  is terrible for me*

### What Happened Instead

black screens*

### Additional Details

IDK*

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Please fill out the form
