### ISSUE TITLE
Issue with Spice of Life compat

### ISSUE THREAD

**Issue by CritFlaw** [iPortalTeam/ImmersivePortalsModForForge#68]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

43.2.3

### ImmersivePortals Version

2.3.1-mc1.19.2

### Latest Log

https://gist.github.com/CritFlaw/fd33ae9b85f1adcf224b6df254074c59

### Crash Report (if applicable)

https://pastebin.com/gfLknuSr

### Steps to Reproduce

1. Eat some foods to get your hearts above the normal by at least once
2. Make a nether portal with IP installed, go through, having in my case one of the foods already eaten (baked potato)
3. Eat that food after you've crossed the dimension
4. Crash

### What You Expected

I expected not to crash.

### What Happened Instead

It crashed upon eating the food in the other dimension. In other instances this crashed after coming back to the overworld and eating the food. I can't recall if that's after I restarted from a crash while being in the nether, or first eating the food in the nether and then the overworld, but the point is it happens in both dimensions. 

### Additional Details

I know this is more of an issue with Spice of Life, however it does only happen when Immersive Portals is installed, and it's likely something you should be aware of in case IP has some part in the reason for the crash. The same issue opened on SOL's side is here: https://github.com/Cazsius/Spice-of-Life-Carrot-Edition/issues/143

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Most likely related to #69

**Comment by Nick1st** [comment]
Can you try if the attached version fixes your problem? (Rename it from .zip to .jar) [I somehow can't upload a jar...]
[immersive-portals-2.3.1-mc1.19.2-forge.zip](https://github.com/iPortalTeam/ImmersivePortalsModForForge/files/10385679/immersive-portals-2.3.1-mc1.19.2-forge.zip)

**Comment by CritFlaw** [comment]
Testing the same steps seems to not have a crash. There do however seem to be two issues. One of which may be vanilla portals existing beforehand:
1. There's some kind of empty entity in front of the vanilla portal even after broken
![java_s5DWXeD8k2](https://user-images.githubusercontent.com/22233000/211901234-d34ab31c-34eb-4489-9d9b-8fc9659dc294.png) (this is probably the issue due to vanilla portals existing in the world, but a way to fix this would still be great)

2. The debug menu no longer appears when pressing F3. Happens both on the nether and overworld
![Y5pPsR3xZ9](https://user-images.githubusercontent.com/22233000/211901819-0382a476-c6e1-43fd-a56b-8fefae593b40.png)

**Comment by Nick1st** [comment]
Thanks for the reply. 
The second issue is related to Cloth config, see #71.
The first issue is probably an old portal, those blocks look like portal helper blocks.
