### ISSUE TITLE
Immersive Portals break mods when you move through portal

### ISSUE THREAD

**Issue by RyScrivy** [iPortalTeam/ImmersivePortalsModForForge#69]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

No

### Forge Version

43.2.3

### ImmersivePortals Version

2.3.1-mc1.19.2

### Latest Log

n/a

### Steps to Reproduce

1. Create any immersive portal and allow chunks to load
2. Move through the portal 
3. If using MrCrayFish Gun mod, attempt to shoot gun and reload. If using Ars Nouveau, attempt to cast any spell.
4. Both mods fail to work. Doesn't matter if you move back through portal again.
5. If you disconnect from game and log back in, issue is fine. Move through portal again, loses functionality.

If you set the portal mode to 'Vanilla', the issue isn't present. It only is affected with the immersive portal functionality.

### What You Expected

I expected that either mod would continue operating as expected after moving through portal.

### What Happened Instead

Mods broke until you reset the game.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by RyScrivy** [comment]
Hey @Nick1st I just noticed your link to the Spice of Life Compat issue. I used the same file that you provided in that issue and it seems to have resolved the problem. I will keep testing it to see if it continues to work as expected. 

Thanks

**Comment by DatBoiOmonie** [comment]
this still happens
seems to mainly be previlent when u combine spice of life, apple pie edition with immersive portals.
