### ISSUE TITLE
Portals between dimensions cannot be found.

### ISSUE THREAD

**Issue by CowChunks** [iPortalTeam/ImmersivePortalsModForForge#7]
### According to your testing, does the issue occur with ONLY Immersive Portals mod?

Yes

### Forge Version

40.1.73

### ImmersivePortals Version

immersive-portals-1.4.9-rc2-mc1.18.2-forge

### Latest Log

https://gist.github.com/CowChunks/22c54b6b429856d4a1a972e516a7460f

### Steps to Reproduce

1. Set a data pack up that locates a same shaped portal in a different dimension (eg. The Nether) with the option to create a portal if a identical frame cannot be found set to false.
2. Create the two same portals in each of the respective dimensions
3. Light one of the portals

### What You Expected

For a portal to be created at the location of the same frame in the other dimension.

### What Happened Instead

I lit one of the portals and it played the animation of purple particles, then nothing happened. No message appeared.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Please upload the datapack you use

**Comment by CowChunks** [comment]
Here is a google drive link with the pack. Its just crying obsidian for a frame and it only goes from overworld to nether. https://drive.google.com/file/d/16qQm0gqJbPwl4-rBhiP5KYOrMeU79vqG/view?usp=sharing

**Comment by Nick1st** [comment]
This is working as you intend it to work.
Note, to mimic vanilla portal logic, you need to apply from/to scaling:
> space_ratio_from Integer (1 if missing). This side dimension's space ratio.
space_ratio_to Integer (1 if missing). The other side dimension's space ratio. Together with the above defines the space mapping. For example, 8 blocks' length in overworld corresponds to 1 block's length in the nether. The overworld's space ratio is 8 and the nether's space ration is 1.

 Otherwise, the coordinates of the frames need to match.
