### ISSUE TITLE
looking at a portal after entering causes game to crash and makes screen flash white very fast

### ISSUE THREAD

**Issue by SmashHits** [iPortalTeam/ImmersivePortalsModForForge#70]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

43.1.7

### ImmersivePortals Version

2.3.1-mc1.19.2

### Latest Log

game acts as if it wasn't broken

### Crash Report (if applicable)

game acts as if it wasn't broken

### Steps to Reproduce

1. build and light nether portal
2. if it doesn't load walk through the portal
3. once at the other side looking at the portal for a brief period of time will crash the game and flash white

### What You Expected

the portal not loading on the other side or loading after given enough time

### What Happened Instead

game stopped responding and the entire screen flash white on and off

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Post. The. Logs.

**Comment by Nick1st** [comment]
Closed due to missing response. If any1 can reproduce this in a newer version, feel free to open a new issue.
