### ISSUE TITLE
incompatible with create trains 43.

### ISSUE THREAD

**Issue by xXjojojXx** [iPortalTeam/ImmersivePortalsModForForge#73]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

43.2.3

### ImmersivePortals Version

portals-1.4.13-mc1.18.2-

### Latest Log

0

### Crash Report (if applicable)

0

### Steps to Reproduce

build portal rails lay rails blocked drive through rails

### What You Expected

without your mod the create train can drive through the portal and of course back without any problems

### What Happened Instead

 0

### Additional Details

 0

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by xXjojojXx** [comment]
https://www.youtube.com/watch?v=Weg1aYDVrsw&t=129s

**Comment by Nick1st** [comment]
#32
