### ISSUE TITLE
My server crash when I open it with the Mod.

### ISSUE THREAD

**Issue by Cpido** [iPortalTeam/ImmersivePortalsModForForge#8]
### According to your testing, does the issue occur with ONLY Immersive Portals mod?

Yes

### Forge Version

40.1.73

### ImmersivePortals Version

1.4.9-mc1.18.2

### Latest Log

https://gist.github.com/Cpido/8a182cc393444f588d46fee51fa79905

### Crash Report (if applicable)

https://gist.github.com/Cpido/d8cdea13d68366e14223af7d807716db

### Steps to Reproduce

1. Start Server

### What You Expected

I thought it would start without a problem, maybe with some incompatibility of some mod but my thought was to start the server with the mod without a problem.

### What Happened Instead

When I started the server it crash, I check if it was a problem of some other mod due to incompatibility but when doing a test with the mod alone (immersive portals) the server crashed because of it.

### Additional Details

Maybe it's stupid to say it, but maybe because I'm setting up the server on Ubuntu? I think there should be no problem with that, but just in case.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Please try the latest pre-release.

**Comment by Cpido** [comment]
> Please try the latest pre-release.

I tried it and it works perfectly! I've tried it with other mods too and so far I haven't had any problems :) Thanks for fixing it, I appreciate it!
