### ISSUE TITLE
crash the server arclight 1.19.2, player dead and when it collides

### ISSUE THREAD

**Issue by iFrzdy** [iPortalTeam/ImmersivePortalsModForForge#81]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

43.3.4

### ImmersivePortals Version

2.3.2-1.19.2

### Latest Log

https://gist.github.com/Fr3dyx/6dab9556d391cfc159474e09e652d27f

### Crash Report (if applicable)

https://gist.github.com/Fr3dyx/b63a253cc23d4971541e01facdd9f3fd

### Steps to Reproduce

the error applies to the moment of chacer tp to the players, from under the ground and to the dead.

### What You Expected

I thought that some mod crashed with the immersive

### What Happened Instead

I have nothing to write xd

### Additional Details

it was without plugins or mods, just performance mods like rubidium smootbot and spark. this only happens on arclight servers since it doesn't happen on forge servers.
Video link (expires in one day) 
![crashh](https://user-images.githubusercontent.com/121781881/216616926-0b6a61ca-57b2-4aa8-a187-f8b092bc6266.PNG)
https://streamable.com/mmkrce
(Note:
I did not want to confirm that it did not happen to me in a hybrid server but it did not let me pass.)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [ ] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
> I did not want to confirm that it did not happen to me in a hybrid server but it did not let me pass.

That's on purpose. I am sadly not able to support hybrids.
