### ISSUE TITLE
Looking at active portal causes world around to go black!

### ISSUE THREAD

**Issue by Tomatoe1** [iPortalTeam/ImmersivePortalsModForForge#82]
Installed the latest version for 1.19.2 and have an issue with the world around the portal being blacked out when looking at the portal. It works just fine in my game, just a visual glitch as far as I've observed!

**Comment by RemagOfficial** [comment]
do you have optifine installed or any other mods!

**Comment by Tomatoe1** [comment]
I just reloaded my game after I updated the to the latest forge version and it's working just fine and no bugs or glitches!

**Comment by Tomatoe1** [comment]
Also, I don't have optifine either. I don't really know what it glitched, but like I said, it's working great now!
