### ISSUE TITLE
Can only see a few blocks out when looking through the portal

### ISSUE THREAD

**Issue by Scifantech** [iPortalTeam/ImmersivePortalsModForForge#84]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

43.2.3

### ImmersivePortals Version

2.3.1 - mc1.19.2

### Latest Log

https://gist.github.com/Scifantech/b92330eb6d2067ad57d0ddac45c53535

### Steps to Reproduce

All I did was create the portal ignited it and it is solid grey until you get right up on the portal then you can see a few blocks in. As soon as you enter it then you can see the whole dimension.

### What You Expected

When I use to use Immersive Portals back in mc1.12.2 when you looked through the portal you could see way off in the distance.

### What Happened Instead

With this version i can only see abut 4 to 6 blocks into the dimension then nothing but grey after that.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Log contains Optifine.
