### ISSUE TITLE
Immersive Portals mod does not load in Forge

### ISSUE THREAD

**Issue by maximilian-schwaerzler** [iPortalTeam/ImmersivePortalsModForForge#85]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

43.2.0

### ImmersivePortals Version

2.3.1-mc1.19.2-forge

### Latest Log

https://gist.github.com/magical-obama/343cede26711c90536e407ece7638d16

### Steps to Reproduce

1. Install IP Mod
2. Launch MC Forge
3. See exception in the log
4. Mod does not appear in Forge mod overview

### What You Expected

That the mod shows up in the overview.

### What Happened Instead

The mod did not load

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by maximilian-schwaerzler** [comment]
PS: In the log it says 1.16.5 but i have confirmed that it also doesn't work with 1.19.2 [here](https://gist.github.com/magical-obama/e8acea37de546fea2180a1f98e6071ce)

**Comment by Nick1st** [comment]
You're using the fabric jar
