### ISSUE TITLE
Player doesn't render if... 

### ISSUE THREAD

**Issue by Acat1234** [iPortalTeam/ImmersivePortalsModForForge#88]
### According to your testing, does the issue occur with ONLY Immersive Portals mod installed?

Yes

### Forge Version

43.2.4

### ImmersivePortals Version

2.3.3-mc-1.19.2

### Latest Log

idk what a "log" is or how to find it.

### Steps to Reproduce

make a nether portal make it unbreakable then break the frame go into the portal not fully then use F5 2 times have the camera look from the overworld something like this
![2023-03-13_11 39 43](https://user-images.githubusercontent.com/126712560/224798799-9ab40d40-1e7e-4020-bbb3-6769b52f03c0.png)
then look forward instead of the side as shown in last image and this will likely happen
![2023-03-13_11 39 45](https://user-images.githubusercontent.com/126712560/224799246-2abdfc95-a889-44fb-bd1d-e6dc75b9773a.png)

### What You Expected

um to render correctly ok?

### What Happened Instead

as seen before

### Additional Details

1. I don't play on fabric version so I can't test it.
2. I did test it with and without Optifine it seems to be an incompatibility with Optifine and I need optifine for FPS boost can it get fixed please?

### Please Read and Confirm The Following

- [x] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed I'm not using a hybrid server (Magma, Cauldron) or a different (non official) Forge Server release.
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Lolothepro** [comment]
https://qouteall.fun/immptl/wiki/#mod-compatibility
Please don't use Optifine.

**Comment by Nick1st** [comment]
Use Rubidium instead

**Comment by Acat1234** [comment]
ok
