### ISSUE TITLE
tconstruct bouncy state is removed when traveling through a portal 

### ISSUE THREAD

**Issue by spx01** [iPortalTeam/ImmersivePortalsModForForge#9]
### According to your testing, does the issue occur with ONLY Immersive Portals mod?

No

### Forge Version

40.1.73

### ImmersivePortals Version

1.4.9-rc3-1.18.2

### Latest Log

-

### Steps to Reproduce

1. Use an immersive portal to reach nether
2. Test the Bouncy modifier from tconstruct by falling from somewhere high

### What You Expected

Fall damage is prevented

### What Happened Instead

Fall damage is dealt

### Additional Details

This doesn't happen when using vanilla portals (even in the presence of the mod)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this does not happen on the fabric version (If it does please report to **[here](https://github.com/iPortalTeam/ImmersivePortalsMod/issues)** instead).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Nick1st** [comment]
Please attach your log. There are reasons I made it a mandority 😄!

Also, for a mod-compat issue, the first question should always be answered `No`.

**Comment by spx01** [comment]
Here is the log: https://gist.github.com/spx01/6f0396e518f523cc195440510080f204

**Comment by Nick1st** [comment]
Fixed in the latest version.
